### ISSUE TITLE
Update monolog dependencies

### ISSUE THREAD

**Issue by batangaTroy** [andriesss/monolog-gdpr#3]
Hello, Our project is fixed to Monolog 2.3.* currently. Looking through the code, I see little reason to think your processors wouldn't work above **monolog/monolog ^1.17**

Do you mind if I update the composer.json dependency and make a pull request?

**Comment by rimas-kudelis** [comment]
@batangaTroy did you end up doing this?

**Comment by batangaTroy** [comment]
@rimas-kudelis no but glad to see the change.

**Comment by andriesss** [comment]
Thanks! Support for v2 was added in #4 by @rimas-kudelis and tagged in v2.0
